#
# Makefile for 'medsea_west' setup.
#

name	= medsea_west
setup	= $(name)

include ../Rules.make

$(name)_clean:

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
