#
# Makefile for 'gotland' setup.
#

name	= gotland
setup	= $(name)

include ../Rules.make

$(name)_clean:

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
