#
# Makefile for 'inflows' setup.
#

name	= inflows
setup	= $(name)

include ../Rules.make

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
