#
# Makefile for 'nns_seasonal' setup.
#

name	= nns_seasonal
setup	= $(name)

include ../Rules.make

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
