#
# Makefile for 'lago_maggiore' setup.
# targets are:
#

name	= lago_maggiore
setup	= $(name)

include ../Rules.make

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
