#
# Makefile for 'nns_annual' setup.
#

name	= nns_annual
setup	= $(name)

include ../Rules.make

$(name)_clean:

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
