#
# Makefile for 'flex' setup.
#

name	= flex
setup	= $(name)

include ../Rules.make

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
