#
# Makefile for 'liverpool_bay' setup.
#

name	= liverpool_bay
setup	= $(name)

include ../Rules.make

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
