#
# Makefile for 'medsea_east' setup.
#

name	= medsea_east
setup	= $(name)

include ../Rules.make

$(name)_clean:

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
